-- Initial schema matching the JSON files currently used by Dressupgame.
-- Express still reads JSON until routes are switched over; this lets the
-- GitHub integration apply a real database when you push.

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  roles text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id bigint primary key references public.app_users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.items (
  id text primary key,
  filename text,
  name text,
  slot_id text,
  tags jsonb not null default '[]'::jsonb,
  heart boolean not null default false,
  designer text not null default '',
  is_set boolean not null default false,
  default_x integer not null default 0,
  default_y integer not null default 0,
  default_z integer not null default 0,
  golden_ticket_price integer not null default 0,
  frame_count integer not null default 1,
  sprite_sheet_frame_w integer not null default 0,
  sprite_sheet_frame_h integer not null default 0,
  image_url text,
  extra jsonb not null default '{}'::jsonb
);

create table if not exists public.forum_topics (
  id text primary key,
  topic text not null,
  category text,
  author text,
  author_id bigint references public.app_users(id) on delete set null,
  created_at timestamptz,
  latest_post timestamptz,
  last_commenter text,
  locked boolean not null default false,
  extra jsonb not null default '{}'::jsonb
);

create table if not exists public.forum_posts (
  id text primary key,
  topic_id text references public.forum_topics(id) on delete cascade,
  parent_id text,
  user_id bigint references public.app_users(id) on delete set null,
  username text,
  message text,
  extra jsonb not null default '{}'::jsonb,
  created_at timestamptz
);

create index if not exists forum_posts_topic_id_idx on public.forum_posts (topic_id);

create table if not exists public.messages (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.outfits (
  user_id bigint not null references public.app_users(id) on delete cascade,
  name text not null,
  items jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (user_id, name)
);

create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  game text not null,
  username text not null,
  score integer not null,
  created_at timestamptz not null default now()
);

create index if not exists game_scores_game_score_idx on public.game_scores (game, score desc);

create table if not exists public.projects (
  id text primary key,
  name text,
  released boolean not null default false,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz
);

create table if not exists public.dashboard_slides (
  id text primary key,
  data jsonb not null default '{}'::jsonb
);

create table if not exists public.site_settings (
  id text primary key default 'default',
  data jsonb not null default '{}'::jsonb
);

-- Catch-all for remaining JSON files until they are modeled
-- (vintage, equipped, hover-card-foil, stickers, emotes, gifs, reports, submissions).
create table if not exists public.json_store (
  key text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- Express uses the service role key, which bypasses RLS.
-- Keep the public anon key from reading or writing these tables directly.
alter table public.app_users enable row level security;
alter table public.profiles enable row level security;
alter table public.items enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_posts enable row level security;
alter table public.messages enable row level security;
alter table public.outfits enable row level security;
alter table public.game_scores enable row level security;
alter table public.projects enable row level security;
alter table public.dashboard_slides enable row level security;
alter table public.site_settings enable row level security;
alter table public.json_store enable row level security;
